# Generated by Django 6.0.7 on 2026-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, unique=True
            ),
        ),
    ]
