# Generated by Django 6.0.7 on 2026-08-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID задачи Celery"
            ),
        ),
    ]
