# Generated by Django 6.0.7 on 2026-08-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notification",
            field=models.DateField(
                blank=True, null=True, verbose_name="Время последнего оповещения"
            ),
        ),
    ]
