# Generated by Django 6.0.7 on 2026-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_last_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="last_notification",
        ),
        migrations.AddField(
            model_name="habit",
            name="next_notification",
            field=models.DateField(
                blank=True, null=True, verbose_name="Время следующего оповещения"
            ),
        ),
    ]
