# Generated by Django 6.0.7 on 2026-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_remove_habit_last_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="next_notification",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время следующего оповещения"
            ),
        ),
    ]
