# Generated by Django 6.0.7 on 2026-08-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_next_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="notifications_on",
            field=models.BooleanField(
                default=False, verbose_name="Уведомления включены"
            ),
        ),
    ]
