# Generated by Django 6.0.7 on 2026-08-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_habit_notifications_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
